Popup design DOM
Kajal19-del/First_Portfolio pull request #12
Opened 2023-02-02 17:46 UTC by Kajal19-del

2023-02-02 18:43 UTC, omarsalem7 requested changes
Hi @Kajal19-del 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper title and description. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 18:43 UTC, omarsalem7 commented on app.js
> +  </div>
- [ ] Kindly adjust the design for the image for the project to match the Figma design.

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/216416106-3c18c247-f7e8-4fd5-b3a1-2ce4b3c95ace.png) | ![image](https://user-images.githubusercontent.com/53402600/216416369-40e4c9b0-6db8-4688-b69e-3edaade75246.png) |

2023-02-02 18:43 UTC, omarsalem7 commented on app.js
> +    popUp.classList.toggle('hide');
- [ ] Kindly make sure when you click on the see project button the corresponding popup modal contains info about the opened project with details about it not the same one for every modal.

- [ ] Also consider adjusting the size of the image in the modal to match the one in the Figma design, kindly take a look at the following image for Modal in the Figma design 
>![image](https://user-images.githubusercontent.com/53402600/216420097-f9c499e9-435e-422f-9681-98f53b3e0f2d.png)

2023-02-03 00:08 UTC, Kajal19-del commented on app.js
> +  </div>
Hello @omarsalem7, can you please clarify the changes please. Is it the image size you want me to change?

2023-02-03 00:43 UTC, mikethreels approved these changes
Hi Kajal, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 08:34 UTC, merged